/// Flutter icons BrightApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BrightApp
///      fonts:
///       - asset: fonts/BrightApp.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class BrightApp {
  BrightApp._();

  static const _kFontFam = 'BrightApp';

  static const IconData play_circle_outline = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData add = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData remove = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData apartment = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData cart = const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData map_marker = const IconData(0xe833, fontFamily: _kFontFam);
  static const IconData alarm = const IconData(0xe858, fontFamily: _kFontFam);
  static const IconData magnifier = const IconData(0xe86f, fontFamily: _kFontFam);
  static const IconData arrow_left = const IconData(0xe879, fontFamily: _kFontFam);
  static const IconData arrow_right = const IconData(0xe87a, fontFamily: _kFontFam);
}
